### ISSUE TITLE
 Pressing backtick replaces selection instead of wrapping it

### ISSUE THREAD

**Issue by Yajo** [vscode-restructuredtext/vscode-restructuredtext#62] opened 2017-09-29 07:40 UTC
Reopening https://github.com/Microsoft/vscode/issues/35029 in the right place:

---

- VSCode Version: Code 1.16.0 (787b31c0474e6165390b5a5989c9619e3e16f953, 2017-09-06T16:19:37.192Z)
- OS Version: Linux x64 4.12.13-300.fc26.x86_64
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
EditorConfig|Edi|0.10.1
vscode-docker|Pet|0.0.18
python|don|0.7.0
restructuredtext|lex|37.0.0
hg|mrc|1.1.7
language-gettext|mro|0.0.2
qub-xml-vscode|qub|1.2.8
sass-indented|rob|1.4.2

---

Steps to Reproduce:

1. Write `hello`
2. Select `hello`
3. Press `"` ➡️ it becomes `"hello"` ✔️ 
4. Press `` ` `` (backtick) ➡️ it becomes ``"`"`` 🚫  ➡️ it should become ``"`hello`"``

Reproduces without extensions: Yes

**Comment by lextm** [comment] 2017-09-29 13:36
What exactly are the keys on the keyboard you press in step 3? I could not understand what you mean.

**Comment by Yajo** [comment] 2017-10-02 07:13
The key that writes a double quote, it may be different depending on your keyboard layout.
In step 4, it's the key that writes a backtick. In RST, backticks are used to indicate links or (when double) inline code. As such, when pressing a backtick with a word selected, the word should get surrounded by backticks, instead of replaced by one.

**Comment by lextm** [comment] 2017-10-02 13:23
Technically speaking, this extension does not handle any keyboard input at all. 

I am interested in what gives you the nice behavior of step 3. I could not reproduce that on my machine. So maybe you should tell what is your keyboard layout and what exactly are the keys you press in each step, so I might gain better insight.

**Comment by Yajo** [comment] 2017-10-03 07:39
I don't think the key itself matters, but the character written.

In any case, I use a spanish keyboard, and I press shift+2 to get the `"` character, and I press twice the `` ` `` key to get it printed too.

**Comment by lextm** [comment] 2017-10-03 14:47
I did a few test cases on macOS High Sierra based on your description and it seems,

**Test cases**

1. Select some text in a specific language file.
2. Input `"` or `` ` ``.

**Result**
* Batch: Autocompletion for `"`, but not for `` ` ``.
* YAML: Autocompletion for `"`, but not for `` ` ``.
* Markdown: Autocompletion for `` ` ``, but not for `"`.
* Restructured Text: Autocompletion for neither.

So far it is not clear to me which part of Visual Studio Code handles the autocompletion, but clearly not from this extension itself.

Close it temporarily. Once we are sure what to do, then this can be re-opened.

**Closed by lextm** 2017-10-03 14:47 UTC
Labels: more info needed

**Comment by lextm** [comment] 2017-10-04 13:27
You can upgrade to release 38.0.0. I do add some language configuration.

However, you should notice that
* `` ` `` is supported, as it is commonly used as reStructuredText syntax.
* `"` is not supported, as it is not part of reStructuredText syntax. Markdown does not support it either.
