### ISSUE TITLE
Autosurround text with parenthesis/brackets does not work

### ISSUE THREAD

**Issue by ArtFlag** [vscode-restructuredtext/vscode-restructuredtext#63] opened 2017-10-09 10:31 UTC
**Environment**
- [ ] Extension version: 38.0.0
- [ ] Visual Studio Code version: 1.17.0
- [ ] Operating System version: macOS Sierra 10.12.6
- [ ] Python version: 2.7.10
- [ ] sphinx version: 1.6.4
- [ ] A sample of conf.py or its important fragments:

**Expected behavior**

1. Type some text in an .rst file.
2. Select it.
3. Press `(` or `[`. 

The selected text is surrounded by the pressed character.

**Actual behavior**

1. Type some text in an .rst file.
2. Select it.
3. Press `(` or `[`. 

The text is replaced by the pressed character.

**More info**

I have tried this with the rst extension disabled and enabled, it seems the issue is related to this extension. Not sure the extension itself is the culprit but the behavior is fixed when I disable it.

Weirdly enough, when I have the extension on, I can select text and surround it with `*`/ ` `` `  without problems.
When the extension is off, the selected text is replaced by `*`/ ` `` ` .  Maybe that helps.

**Comment by lextm** [comment] 2017-10-09 14:40
`(` and `[` are useful in Markdown (but the Markdown extension does not auto-surround them either), but not in reStructuredText. Therefore, we don't support them at all.

Closed as by design.

**Closed by lextm** 2017-10-09 14:40 UTC
