### ISSUE TITLE
Feature request - format .rst file

### ISSUE THREAD

**Issue by oharboe** [vscode-restructuredtext/vscode-restructuredtext#175] opened 2019-08-21 05:29 UTC
I'd like to be able to format .rst files on save.

Formatting on save has become quite a standard part of the workflow these days as it makes it trivial to define and enforce a code formatting standard: it's done automatically.

**Comment by lextm** [comment] 2019-08-25 22:28
Duplicate of #51

**Closed by lextm** 2019-08-25 22:28 UTC
Labels: duplicate
