### ISSUE TITLE
How to preview README.rst at project top level?

### ISSUE THREAD

**Issue by zillionare** [vscode-restructuredtext/vscode-restructuredtext#246] opened 2020-11-10 02:50 UTC
This is a great exentsion, I love it. It works just fine, however, it fail in this case:

If you put a README.rst in proejct top level folder, and other doc files are in docs, like this:

my project:
    \README.rst
    \src
    \docs
            \index.rst
            \readme.rst
            \_build
   
in readme.rst, it includes README.rst
```
.. include:: ../README.rst
```
if you preview readme.rst, everything works just fine. But if you choose to preview README.rst (the top level), it failed with:
```
Detailed error message
Error
ENOENT: no such file or directory, open '/mnt/c/workspace/omega/docs/_build/README.html'
Error: ENOENT: no such file or directory, open '/mnt/c/workspace/omega/docs/_build/README.html
```
the project layout is quite normal, it's suggested by cookie-cutter. And github will render README.rst at project top level as main document to user, so cannot move it into docs folder.

Wondering why no other guys report same issue, is there an workaround here?

**Environment**
- [ ] Extension version: v129.0.0
- [ ] Visual Studio Code version: 1.51.0
- [ ] Operating System version: Windows_NT x64 10.0.19042
- [ ] Python version: 3.8.2 64 bit
- [ ] sphinx version: 1.2.1
- [ ] A sample of conf.py or its important fragments:

**Expected behavior**
README.rst at the top level can be previewed as I edit it.
**Actual behavior**
Can't preview README.rst by itself. I have to edit the file, switch to readme.rst, then choose open preview.

**Detailed Steps to reproduce the problem**

**Comment by lextm** [comment] 2020-11-10 03:28
It is by design.

Sphinx does not generate an HTML page for your top level readme file (as it is included as part of the child readme file as source code), and that's what the error message means. Thus, there is nothing to preview.

**Comment by zillionare** [comment] 2020-11-11 07:38
Any chance to have a workdaround? A readme file at project level is very common practice.

**Comment by Notmarrco** [comment] 2020-11-19 18:22
perhaps allow some files to be viewed only with docutils ?

**Comment by akai10tsuki** [comment] 2020-12-23 00:01
To view the readme file what I do is make a symbolic link of the README.rst file in the source directory for sphinx.  Sphinx will give you a warning:

## README.rst: WARNING: document isn't included in any toctree

but you will se the preview.

**Comment by lextm** [comment] 2024-01-05 07:36
Starting from version 190.1.17, this extension no longer performs live preview or language server based actions but recommends the Esbonio extension to be used instead. Close this issue now.

**Closed by lextm** 2024-01-05 07:36 UTC
Labels: question
