### ISSUE TITLE
Python.exe task don't close when closing vscode

### ISSUE THREAD

**Issue by EitanSomething** [vscode-restructuredtext/vscode-restructuredtext#211] opened 2020-05-07 16:38 UTC
Please follow [the troubleshooting guide](https://docs.restructuredtext.net/articles/troubleshooting.html) to locate the culprit.

If troubleshooting does not reveal any useful information, provide the following information to create a new issue,

**Environment**
- [ 126.0.0] Extension version:
- [1.44.2 ] Visual Studio Code version:
- [ windows 10] Operating System version:
- [ 3.82] Python version:
- [ 2.3.1] sphinx version:
- [ ] A sample of conf.py or its important fragments:

**Expected behavior**
python.exe task end when closing vscode
**Actual behavior**
python.exe tasks still run after closing vscode and need to be ended manually from task manager

**Detailed Steps to reproduce the problem**
open vscode with reStructuredText setup
select .rst file from explorer
Press Open Preview to the side
close vscode

**Comment by lextm** [comment] 2020-05-07 17:18
"python.exe task end when closing vscode" is not likely to happen.

Child processes are not killed by parent processes in general.

**Comment by EitanSomething** [comment] 2020-05-07 17:54
If the python.exe can't be closed by when closing vscode I will have to deal with it, but I would assume they would be ended when closing vscode because they are created by vscode-restructuredtext.

Before closing vscode
![Annotation 2020-05-07 135029](https://user-images.githubusercontent.com/37350423/81327773-cb992a80-9069-11ea-8fe6-cad8decef01c.png)

After closing vscode
![Annotation 2020-05-07 135202](https://user-images.githubusercontent.com/37350423/81327855-f1beca80-9069-11ea-8091-72593b0c1e01.png)

**Comment by lextm** [comment] 2020-05-07 18:43
I cannot reproduce that with simple test files, such as https://github.com/vscode-restructuredtext/vscode-restructuredtext/tree/125.0.0/test-resources/sphinx So I wonder what kind of files you are working on. Without further details, it is impossible to analyze the possible causes.

**Comment by EitanSomething** [comment] 2020-05-07 18:50
I am using the files from here.
https://svn.blender.org/svnroot/bf-manual/trunk/blender_docs

the config.py is under bledner_docs/manual

Here are instruction on how to install https://docs.blender.org/manual/en/latest/about/contribute/install/index.html

settings.json
`{
    "restructuredtext.builtDocumentationPath": "${workspaceRoot}\\build\\html",
    "restructuredtext.updateOnTextChanged"    : "true",
    "restructuredtext.updateDelay"            : 300,
    "restructuredtext.confPath": "${workspaceFolder}\\manual"
}
`

**Comment by lextm** [comment] 2020-05-08 19:46
Actually I had to download all your files and reproduced the issue, so as to identify what was the cause and what might be the workaround.

I got some progress and will write about it when I finish.

**Comment by lextm** [comment] 2020-05-08 20:25
There isn't much this extension can help. Your project is huge, so it takes minutes for Python (sphinx) to build the HTML pages for preview (it generates not only a single page, but all pages for the whole project). Therefore, if you close VSCode before Python.exe finishes, it remains there in Task Manager.

The workaround is to run build.bat to generate the pages for the first time, before you open VSCode and start to preview a page. That warmup actually reduces the time taken by python.exe launched afterward, so such processes can exit quickly and you don't need to kill them manually any more.

It is a price to pay in order to get accurate preview results. But if you don't like this, switch to docutil engine to preview.

**Closed by lextm** 2020-05-08 20:25 UTC
Labels: area:preview, faq candidate

**Comment by EitanSomething** [comment] 2020-05-08 20:56
Thank you

**Comment by lextm** [comment] 2022-02-28 00:42
Release 172.0.0 uses Esbonio language server to provide live preview, which provides much better performance, so this issue is considered resolved.
