### ISSUE TITLE
PlantUML svg not displayed

### ISSUE THREAD

**Issue by danlkv** [vscode-restructuredtext/vscode-restructuredtext#308] opened 2021-07-17 23:54 UTC
Hi! The extension doesn't display svg output from plantuml. PNG works fine. Building with `make html` and viewing in browser works fine as well.

**Environment**
- [x] Extension version: 155.0.0
- [x] Visual Studio Code version: 1.58.2
- [x] Operating System version: WSL Ubuntu 20.40 Windows 11
- [x] Python version: 3.8.2
- [x] sphinx version: 3.4.3
- [x] A sample of conf.py or its important fragments:

```python
extensions = [
    'sphinxcontrib.plantuml'
]
plantuml = 'java -jar ../plantuml.jar'
plantuml_output_format = 'svg'
```

**Expected behavior**
SVG is rendered in my VSCode preview for my plantUML code in rst file.

**Actual behavior**
No picture is displayed in preview, however `make html` produces correct output.

**Detailed Steps to reproduce the problem**

1. Install java
2. Download latest plantUML from their website
3. Install sphinxcontrib-plantuml
4. Set `plantuml_output_format = 'svg'`
5. Try to preview some diagram

**Comment by lextm** [comment] 2022-03-09 05:55
It is challenging to hook SVG images to webView so more investigation is needed.

**Comment by dinomight** [comment] 2022-04-02 14:44
I'm wondering if this is still a problem. My team recently ran into this specific issue where the SVG wasn't rendering in VSCode, but I just tried today and the SVG *is* rendering. I double checked the HTML and it indeed is using an object to pull the SVG into the HTML page. [This ticket from VSCode](https://github.com/microsoft/vscode/issues/128714) seems to suggest that a lack of SVG support was by design. [Yet another ticket](https://github.com/microsoft/vscode/issues/75931) says that it's now allowed (notice how the second is from 2019 and the first was from 2021, so very odd).

- [x] Extension version: 184.0.0
- [x] VS Code version: 1.66.0
- [x] Operating System: Windows
- [x] Python version: 3.9.11
- [x] Sphinx version: 4.5.0
- [x] PlantUML version: 1.2022.3
- [x] sphinxcontrib-plantuml version: 0.23

Not sure if someone else can confirm, but maybe this is no longer an issue on the latest VSCode?
![image](https://user-images.githubusercontent.com/628102/161388396-b7756e18-4dd7-4c4a-b935-def5410a0659.png)

**Comment by AlexanderLanin** [comment] 2022-09-08 07:50
This issue still persists for me. svg doesn't show in preview. html looks fine. VS Code version 1.71.0

**Comment by lextm** [comment] 2024-01-05 07:34
Starting from version 190.1.17, this extension no longer performs live preview but recommends the Esbonio extension to be used instead. Close this issue now.

**Closed by lextm** 2024-01-05 07:34 UTC
Labels: up for grab, in progress, area:preview
