### ISSUE TITLE
Snooty Language Client - A request has failed. See the outuput, except Output is cleared 

### ISSUE THREAD

**Issue by LiveFreeAndRoam** [vscode-restructuredtext/vscode-restructuredtext#342] opened 2022-01-13 20:16 UTC
### Expected behavior

In case it matters, this is running vscode in a remote-SSH environment.

When reloading/starting VSCode, reStructedText starts the Snooty Language Server. In the `Snooty Language Client` output log, I can see:

```
INFO:snooty.main:Snooty 1.11.6 starting
INFO:snooty.language_server:Started
INFO:snooty.language_server:Parsing
```

After several minutes of running the langugage server, the VSCode pops up an error: "_A request has failed. See the output for more information. Source: reStructuredText (Extension)_"

![image](https://user-images.githubusercontent.com/8231064/149400276-cc43df57-24fb-4d10-be39-b4bfd94e6f2e.png)

When I select "_Go to ouput_" it takes me to the "Snooty Language Client" output, but it has been cleared.
So it's not possible to troubleshoot further.

I also checked the reStructuredText output, but its last line simply logged: `Use Snooty language server`

### Actual behavior

Snooty Language Client log output is cleared on error.

### Detailed steps

I enabled reStructuredText extension and let it do its thing.  I see this on reload and restart of VSCode.  I am not sure what causes the Snooty Client request to fail.

### Extension information

v168.0.0

### Visual Studio Code information

1.63.2

### Operating system information

Windows 10

### Python information

3.10.1

### Sphinx information

Unknown - how do I show this?

### Contents of conf.py

```python
I have no conf.py file. Should I?
```

### Relevant log output

```shell
Output is cleared, so this makes it impossible to troubleshoot.
```

**Comment by lextm** [comment] 2022-01-14 00:54
You can disable snooty by following https://docs.restructuredtext.net/articles/configuration.html#intellisense

I think missing `conf.py` can be the cause, but more investigation is needed.

**Comment by LiveFreeAndRoam** [comment] 2022-01-14 01:16
According to that link, the way I interpret the text is that the
language server is supposed to be disabled by default. Though that does not
seem to align with this observed behavior.   Is that correct?

Extract:

Its default content is as below,

{
    "restructuredtext.languageServer.disabled": true}

**Comment by LiveFreeAndRoam** [comment] 2022-01-14 01:18
According to that link, the way I interpret the text is that the
language server is supposed to be disabled by default. Though that does not
seem to align with this observed behavior.   Is that correct?

Extract:
```
Its default content is as below,

{
    "restructuredtext.languageServer.disabled": true
}
```

**Comment by lextm** [comment] 2022-01-15 18:05
Just did some investigation on Windows. Missing `conf.py` does not seem to be relevant. But I could not reproduce the part of "After several minutes of running the langugage server, the VSCode pops up an error". Need more information here.

**Comment by LiveFreeAndRoam** [comment] 2022-01-15 21:00
The log file is being cleared unexpectedly.  Under what circumstances is the log file cleared or overwritten?

Investigating that may help to narrow down the cause.

**Comment by lextm** [comment] 2022-02-26 18:34
Closed as switching to esbonio.

**Closed by lextm** 2022-02-26 18:34 UTC
Labels: bug, more info needed, area:snooty
