### ISSUE TITLE
Preview no longer works after upgrading to Visual Studio Code 1.59.1 and lextudio.restructuredtext 

### ISSUE THREAD

**Issue by oharboe** [vscode-restructuredtext/vscode-restructuredtext#315] opened 2021-08-31 08:56 UTC
Please follow [the troubleshooting guide](https://docs.restructuredtext.net/articles/troubleshooting.html) to locate the culprit.

If troubleshooting does not reveal any useful information, provide the following information to create a new issue,

**Environment**
- [ ] Extension version: v160.0.0
- [ ] Visual Studio Code version: 1.59.1
- [ ] Operating System version: Ubunut 20.04
- [ ] Python version: 3.8.10
- [ ] sphinx version: 3.4.3
- [ ] A sample of conf.py or its important fragments:

**Expected behavior**

Preview should work

**Actual behavior**

Error loading webview: Error: Could not register service workers: AbortError: Failed to register a ServiceWorker for scope ('vscode-webview://247deae9-2560-48cb-a6a9-e8398571f7e6/') with script ('vscode-webview://247deae9-2560-48cb-a6a9-e8398571f7e6/service-worker.js?id=247deae9-2560-48cb-a6a9-e8398571f7e6&swVersion=2&extensionId=lextudio.restructuredtext&platform=electron&vscode-resource-base-authority=vscode-resource.vscode-webview.net'): Operation has been aborted.

**Detailed Steps to reproduce the problem**

Upgrade, open .rst file, click preview

**Comment by oharboe** [comment] 2021-08-31 09:31
Workaround: downgrade to Visual Studio Code 1.58.2

**Comment by lextm** [comment] 2021-08-31 13:34
At least this does not happen on macOS or Windows. Will try a Ubuntu machine and see if it can be reproduced.

**Comment by lextm** [comment] 2021-08-31 14:36
Cannot reproduce this on a clean Ubuntu 20.04 machine either.

**Comment by oharboe** [comment] 2021-08-31 15:59
@lextm  I can confirm it doesn't happen on all Ubuntu systems. I've tried a very similar system, it doesn't exhibit the problem. More investigation needed.

**Comment by lextm** [comment] 2021-09-01 06:41
Temp close this. We can reopen it when more information becomes available.

**Closed by lextm** 2021-09-01 06:41 UTC
Labels: more info needed

**Comment by oharboe** [comment] 2021-09-01 11:26
It still happened, I tried a number of things:

- git clean -fdx in the project
- reinstalling the latest vscode

The finally I tried something that worked:

pkill code

So... good old: reboot system... Would have fixed this...

There were a number of running "code" processes with various long arguments.  Such as:

```
/usr/share/code/code /usr/share/code/resources/app/out/bootstrap-fork --type=watcherService
```
