### ISSUE TITLE
[Bug]: Latest Update (171.0.0) does not live reload/preview

### ISSUE THREAD

**Issue by AbstractUmbra** [vscode-restructuredtext/vscode-restructuredtext#349] opened 2022-02-27 01:21 UTC
### Expected behavior

I expected the editor to function the same, for the preview to reload live as I edit my RST files as it did in 170.0.0 previously.

### Actual behavior

The editor does not live reload or even reload when I close and re-open, I had to manually build the html with the sphinx-build cli.

### Detailed steps

Update or use version 171.0.0 and open a preview of an RST file (my file is not in a toctree) to the side and make edits to that file.

### Extension information

171.0.0

### Visual Studio Code information

1.64.2

### Operating system information

Linux (Debian 10)

### Python information

3.10.1

### Sphinx information

4.4.0

### Contents of conf.py

```python
#
# discord.py documentation build configuration file, created by
# sphinx-quickstart on Fri Aug 21 05:43:30 2015.
#
# This file is execfile()d with the current directory set to its
# containing dir.
#
# Note that not all possible configuration values are present in this
# autogenerated file.
#
# All configuration values have a default; values that are commented out
# serve to show the default.

import logging
import sys
import os
import re

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
sys.path.insert(0, os.path.abspath('..'))
sys.path.append(os.path.abspath('extensions'))

# -- General configuration ------------------------------------------------

# If your documentation needs a minimal Sphinx version, state it here.
#needs_sphinx = '1.0'

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = [
    'builder',
    'sphinx.ext.autodoc',
    'sphinx.ext.extlinks',
    'sphinx.ext.intersphinx',
    'sphinx.ext.napoleon',
    'sphinxcontrib_trio',
    'details',
    'exception_hierarchy',
    'attributetable',
    'resourcelinks',
    'nitpick_file_ignorer',
]

autodoc_member_order = 'bysource'
autodoc_typehints = 'none'
# maybe consider this?
# napoleon_attr_annotations = False

extlinks = {
    'issue': ('https://github.com/Rapptz/discord.py/issues/%s', 'GH-'),
}

# Links used for cross-referencing stuff in other documentation
intersphinx_mapping = {
  'py': ('https://docs.python.org/3', None),
  'aio': ('https://docs.aiohttp.org/en/stable/', None),
  'req': ('https://docs.python-requests.org/en/latest/', None)
}

rst_prolog = """
.. |coro| replace:: This function is a |coroutine_link|_.
.. |maybecoro| replace:: This function *could be a* |coroutine_link|_.
.. |coroutine_link| replace:: *coroutine*
.. _coroutine_link: https://docs.python.org/3/library/asyncio-task.html#coroutine
"""

# Add any paths that contain templates here, relative to this directory.
templates_path = ['_templates']

# The suffix of source filenames.
source_suffix = '.rst'

# The encoding of source files.
#source_encoding = 'utf-8-sig'

# The master toctree document.
master_doc = 'index'

# General information about the project.
project = 'discord.py'
copyright = '2015-present, Rapptz'

# The version info for the project you're documenting, acts as replacement for
# |version| and |release|, also used in various other places throughout the
# built documents.
#
# The short X.Y version.

version = ''
with open('../discord/__init__.py') as f:
    version = re.search(r'^__version__\s*=\s*[\'"]([^\'"]*)[\'"]', f.read(), re.MULTILINE).group(1)

# The full version, including alpha/beta/rc tags.
release = version

# This assumes a tag is available for final releases
branch = 'master' if version.endswith('a') else 'v' + version

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = None

locale_dirs = ['locale/']
gettext_compact = False

# There are two options for replacing |today|: either, you set today to some
# non-false value, then it is used:
#today = ''
# Else, today_fmt is used as the format for a strftime call.
#today_fmt = '%B %d, %Y'

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
exclude_patterns = ['_build']

# The reST default role (used for this markup: `text`) to use for all
# documents.
#default_role = None

# If true, '()' will be appended to :func: etc. cross-reference text.
#add_function_parentheses = True

# If true, the current module name will be prepended to all description
# unit titles (such as .. function::).
#add_module_names = True

# If true, sectionauthor and moduleauthor directives will be shown in the
# output. They are ignored by default.
#show_authors = False

# The name of the Pygments (syntax highlighting) style to use.
pygments_style = 'friendly'

# A list of ignored prefixes for module index sorting.
#modindex_common_prefix = []

# If true, keep warnings as "system message" paragraphs in the built documents.
#keep_warnings = False


# Nitpicky mode options
nitpick_ignore_files = [
  "migrating_to_async",
  "migrating",
  "whats_new",
]


# Ignore warnings about inconsistent order and/or count of references in translated messages.
# This makes no sense, different languages can have different word order...
def _i18n_warning_filter(record: logging.LogRecord) -> bool:
  return not record.msg.startswith(
    (
      'inconsistent references in translated message',
      'inconsistent term references in translated message',
    )
  )


_i18n_logger = logging.getLogger('sphinx')
_i18n_logger.addFilter(_i18n_warning_filter)

# -- Options for HTML output ----------------------------------------------

html_experimental_html5_writer = True

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
html_theme = 'basic'

html_context = {
  'discord_invite': 'https://discord.gg/r3sSKJJ',
  'discord_extensions': [
    ('discord.ext.commands', 'ext/commands'),
    ('discord.ext.tasks', 'ext/tasks'),
  ],
}

resource_links = {
  'discord': 'https://discord.gg/r3sSKJJ',
  'issues': 'https://github.com/Rapptz/discord.py/issues',
  'discussions': 'https://github.com/Rapptz/discord.py/discussions',
  'examples': f'https://github.com/Rapptz/discord.py/tree/{branch}/examples',
}

# Theme options are theme-specific and customize the look and feel of a theme
# further.  For a list of options available for each theme, see the
# documentation.
# html_theme_options = {
# }

# Add any paths that contain custom themes here, relative to this directory.
#html_theme_path = []

# The name for this set of Sphinx documents.  If None, it defaults to
# "<project> v<release> documentation".
#html_title = None

# A shorter title for the navigation bar.  Default is the same as html_title.
#html_short_title = None

# The name of an image file (relative to this directory) to place at the top
# of the sidebar.
#html_logo = None

# The name of an image file (within the static path) to use as favicon of the
# docs.  This file should be a Windows icon file (.ico) being 16x16 or 32x32
# pixels large.
html_favicon = './images/discord_py_logo.ico'

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ['_static']

# Add any extra paths that contain custom files (such as robots.txt or
# .htaccess) here, relative to this directory. These files are copied
# directly to the root of the documentation.
#html_extra_path = []

# If not '', a 'Last updated on:' timestamp is inserted at every page bottom,
# using the given strftime format.
#html_last_updated_fmt = '%b %d, %Y'

# If true, SmartyPants will be used to convert quotes and dashes to
# typographically correct entities.
#html_use_smartypants = True

# Custom sidebar templates, maps document names to template names.
#html_sidebars = {}

# Additional templates that should be rendered to pages, maps page names to
# template names.
#html_additional_pages = {}

# If false, no module index is generated.
#html_domain_indices = True

# If false, no index is generated.
#html_use_index = True

# If true, the index is split into individual pages for each letter.
#html_split_index = False

# If true, links to the reST sources are added to the pages.
#html_show_sourcelink = True

# If true, "Created using Sphinx" is shown in the HTML footer. Default is True.
#html_show_sphinx = True

# If true, "(C) Copyright ..." is shown in the HTML footer. Default is True.
#html_show_copyright = True

# If true, an OpenSearch description file will be output, and all pages will
# contain a <link> tag referring to it.  The value of this option must be the
# base URL from which the finished HTML is served.
#html_use_opensearch = ''

# This is the file name suffix for HTML files (e.g. ".xhtml").
#html_file_suffix = None

# Language to be used for generating the HTML full-text search index.
# Sphinx supports the following languages:
#   'da', 'de', 'en', 'es', 'fi', 'fr', 'hu', 'it', 'ja'
#   'nl', 'no', 'pt', 'ro', 'ru', 'sv', 'tr'
#html_search_language = 'en'

# A dictionary with options for the search language support, empty by default.
# Now only 'ja' uses this config value
#html_search_options = {'type': 'default'}

# The name of a javascript file (relative to the configuration directory) that
# implements a search results scorer. If empty, the default will be used.
html_search_scorer = '_static/scorer.js'

html_js_files = [
  'custom.js',
  'settings.js',
  'copy.js',
  'sidebar.js'
]

# Output file base name for HTML help builder.
htmlhelp_basename = 'discord.pydoc'

# -- Options for LaTeX output ---------------------------------------------

latex_elements = {
# The paper size ('letterpaper' or 'a4paper').
#'papersize': 'letterpaper',

# The font size ('10pt', '11pt' or '12pt').
#'pointsize': '10pt',

# Additional stuff for the LaTeX preamble.
#'preamble': '',

# Latex figure (float) alignment
#'figure_align': 'htbp',
}

# Grouping the document tree into LaTeX files. List of tuples
# (source start file, target name, title,
#  author, documentclass [howto, manual, or own class]).
latex_documents = [
  ('index', 'discord.py.tex', 'discord.py Documentation',
   'Rapptz', 'manual'),
]

# The name of an image file (relative to this directory) to place at the top of
# the title page.
#latex_logo = None

# For "manual" documents, if this is true, then toplevel headings are parts,
# not chapters.
#latex_use_parts = False

# If true, show page references after internal links.
#latex_show_pagerefs = False

# If true, show URL addresses after external links.
#latex_show_urls = False

# Documents to append as an appendix to all manuals.
#latex_appendices = []

# If false, no module index is generated.
#latex_domain_indices = True


# -- Options for manual page output ---------------------------------------

# One entry per manual page. List of tuples
# (source start file, name, description, authors, manual section).
man_pages = [
    ('index', 'discord.py', 'discord.py Documentation',
     ['Rapptz'], 1)
]

# If true, show URL addresses after external links.
#man_show_urls = False


# -- Options for Texinfo output -------------------------------------------

# Grouping the document tree into Texinfo files. List of tuples
# (source start file, target name, title, author,
#  dir menu entry, description, category)
texinfo_documents = [
  ('index', 'discord.py', 'discord.py Documentation',
   'Rapptz', 'discord.py', 'One line description of project.',
   'Miscellaneous'),
]

# Documents to append as an appendix to all manuals.
#texinfo_appendices = []

# If false, no module index is generated.
#texinfo_domain_indices = True

# How to display URL addresses: 'footnote', 'no', or 'inline'.
#texinfo_show_urls = 'footnote'

# If true, do not generate a @detailmenu in the "Top" node's menu.
#texinfo_no_detailmenu = False

def setup(app):
  if app.config.language == 'ja':
    app.config.intersphinx_mapping['py'] = ('https://docs.python.org/ja/3', None)
    app.config.html_context['discord_invite'] = 'https://discord.gg/nXzj3dg'
    app.config.resource_links['discord'] = 'https://discord.gg/nXzj3dg'
```

### Relevant log output

```shell
## I can see this from the output section of VSC, but no edits are made on the preview to the right, or when I close and re-open it.

[Log - 01:19:11] Successful exec
[Log - 01:19:11] [linter] Execute: "/home/penumbra/projects/other/dpy/.venv/bin/python" -m rstcheck "/home/penumbra/projects/other/dpy/docs/guide/topics/threads.rst" in /home/penumbra/projects/other/dpy.
[Log - 01:19:13] [preview] Compiling file: /home/penumbra/projects/other/dpy/docs/guide/topics/threads.rst
[Log - 01:19:13] [preview] Sphinx conf.py directory: /home/penumbra/projects/other/dpy/docs
[Log - 01:19:13] [preview] Sphinx html directory: /home/penumbra/projects/other/dpy/docs/_build
[Log - 01:19:13] [preview] Working directory: /home/penumbra/projects/other/dpy/docs
[Log - 01:19:13] [preview] HTML file: /home/penumbra/projects/other/dpy/docs/_build/guide/topics/threads.html
[Log - 01:19:13] [preview] Document line count: 189; element count: 0
```

**Comment by AbstractUmbra** [comment] 2022-02-27 01:22
I can confirm 171.0.0 is the issue, after downgrading to 170.0.0 the functionality is restored.

Please let me know if you need any information I may have missed! :)

**Comment by lextm** [comment] 2022-02-27 05:01
Did you see `esbonio: idle` in VSCode status bar?

If not, you have to enable Esbonio language server as now it is a dependency (running sphinx page generation behind the scene for live preview).

**Comment by lextm** [comment] 2022-02-27 07:26
Can you upgrade to 172.0.0 and try again?

**Comment by AbstractUmbra** [comment] 2022-02-27 07:59
Hi, sorry for the delay!

I updated to 172.0.0 and restarted my editor. No live preview and closing and re-opening the preview shows no changes.
My status bar (at the bottom) shows the following:
![Code_2022-02-27_07-58-10](https://user-images.githubusercontent.com/16031716/155873902-9e53b5ff-14b3-4a46-896f-f851a0818834.png)

I do not see the `esbonio: idle` you mentioned. Perhaps I'm missing a config toggle or such?
`esbonio` is definitely installed in the active venv.

**Comment by lextm** [comment] 2022-02-27 18:00
Thanks for sharing the screenshots. Then the cause is clear that esbonio language server was not running.

https://docs.restructuredtext.net/articles/configuration.html#intellisense

Can you check VSCode settings to see if you have previous disabled the language server? We were using snooty and many people chose to disable it.

Enable the language server and see `esbonio: idle` in the status bar. Then live preview should start to work.

**Comment by AbstractUmbra** [comment] 2022-02-28 01:44
You were correct, I had a workspace setting to disable the language server which I seemingly forgotten about. I now have `esbonio: idle` in my status bar.
However when I made an edit, I am now met with this notification:
![Code_2022-02-28_01-40-21](https://user-images.githubusercontent.com/16031716/155910689-eac05b84-f24d-4e80-817a-d8b8bd558282.png)

Upon doing as requested, I only see success messages in the output of the extension:
The output log for the `reStructedText` extension is all fine, but the output of the Esbonio Language Client is the following:

```py
preparing documents...
failed
[esbonio.lsp] Traceback (most recent call last):
  File "/home/penumbra/projects/other/dpy/.venv/lib/python3.10/site-packages/esbonio/lsp/sphinx.py", line 280, in build
    self.app.build()
  File "/home/penumbra/projects/other/dpy/.venv/lib/python3.10/site-packages/sphinx/application.py", line 337, in build
    self.builder.build_update()
  File "/home/penumbra/projects/other/dpy/.venv/lib/python3.10/site-packages/sphinx/builders/__init__.py", line 294, in build_update
    self.build(to_build,
  File "/home/penumbra/projects/other/dpy/.venv/lib/python3.10/site-packages/sphinx/builders/__init__.py", line 358, in build
    self.write(docnames, list(updated_docnames), method)
  File "/home/penumbra/projects/other/dpy/.venv/lib/python3.10/site-packages/sphinx/builders/__init__.py", line 524, in write
    self.prepare_writing(docnames)
  File "/home/penumbra/projects/other/dpy/.venv/lib/python3.10/site-packages/sphinx/builders/html/__init__.py", line 436, in prepare_writing
    self.indexer = IndexBuilder(self.env, lang,
  File "/home/penumbra/projects/other/dpy/.venv/lib/python3.10/site-packages/sphinx/search/__init__.py", line 269, in __init__
    with open(scoring, 'rb') as fp:
FileNotFoundError: [Errno 2] No such file or directory: '_static/scorer.js'
```

This error is common when the cwd of my project is not correct. Perhaps esbonio is not respecting the config values I have set?

```json
{
    "restructuredtext.builtDocumentationPath": "${workspaceFolder}/docs/_build",
    "restructuredtext.confPath": "${workspaceFolder}/docs",
    "restructuredtext.sphinxBuildPath": "${workspaceFolder}/.venv/bin/sphinx-build",
}
```

**Comment by lextm** [comment] 2022-02-28 03:44
Can you add a setting like below? `sphinxBuildPath` is now obsolete.

``` json
{
    "restructuredtext.builtDocumentationPath": "${workspaceFolder}/docs/_build",
    "restructuredtext.confPath": "${workspaceFolder}/docs",
    "restructuredtext.sourcePath": "${workspaceFolder}",
}
```

**Comment by AbstractUmbra** [comment] 2022-02-28 07:25
It seems we're moving further along! The change suggested helped.

It is working to an extent, but the errors are now like this:
```py
... # Truncated many more

/home/penumbra/projects/other/dpy/docs/intents.rst:: WARNING: image file not readable: images/discord_bot_tab.png
[esbonio.lsp] Reporting diagnostic at file:///home/penumbra/projects/other/dpy/docs/intents.rst:1
/home/penumbra/projects/other/dpy/docs/intents.rst:: WARNING: image file not readable: images/discord_privileged_intents.png
[esbonio.lsp] Traceback (most recent call last):
  File "/home/penumbra/projects/other/dpy/.venv/lib/python3.10/site-packages/esbonio/lsp/sphinx.py", line 280, in build
    self.app.build()
  File "/home/penumbra/projects/other/dpy/.venv/lib/python3.10/site-packages/sphinx/application.py", line 337, in build
    self.builder.build_update()
  File "/home/penumbra/projects/other/dpy/.venv/lib/python3.10/site-packages/sphinx/builders/__init__.py", line 294, in build_update
    self.build(to_build,
  File "/home/penumbra/projects/other/dpy/.venv/lib/python3.10/site-packages/sphinx/builders/__init__.py", line 308, in build
    updated_docnames = set(self.read())
  File "/home/penumbra/projects/other/dpy/.venv/lib/python3.10/site-packages/sphinx/builders/__init__.py", line 418, in read
    raise SphinxError('root file %s not found' %
sphinx.errors.SphinxError: root file /home/penumbra/projects/other/dpy/index.rst not found
```

Again this makes me think a setting is not being respected? `index.rst` is within a `docs/` subfolder.

Please let me know if I missed anything!

**Comment by lextm** [comment] 2022-02-28 20:28
Found a few issues in release 172.0.0 when I worked on a similar folder structure. So you need to wait for a new release.

**Comment by AbstractUmbra** [comment] 2022-02-28 21:16
> Can you try to use the following settings?
> 
> ```
> {
>     "restructuredtext.confPath": "${workspaceFolder}/docs"
> }
> ```
> 
> There seems to be a bug on `restructuredtext.builtDocumentationPath` in release 172.0.0, which I am investigating further.

I already had this config in place, as mentioned above! :-) 
Should I try anything more?

**Comment by lextm** [comment] 2022-02-28 21:21
I meant removing all other settings and leaving only `restructuredtext.confPath`. My local testing seems to indicate it should work on your setup.

**Comment by AbstractUmbra** [comment] 2022-03-01 00:16
Removing all settings but that seems like a regression? I now see the following:
![Code_2022-03-01_00-15-15](https://user-images.githubusercontent.com/16031716/156080455-282241a5-12e1-429f-802f-1c5df5528c4a.png)

The path the error mentions is: 
`/home/penumbra/projects/other/dpy/docs/_build/html/guide/topics/threads.html`

Which is correct, the `/home/penumbra/projects/other/dpy/docs/_build/html/` directory is empty. The file was actually output to `/home/penumbra/projects/other/dpy/docs/_build/guide/topics/threads.html`.

**Comment by lextm** [comment] 2022-03-01 04:45
After changing the settings, you need to click "esbonio: idle" to restart the language server. That might generate the page to the right location.

I am also preparing a new release 173.0.0, which might resolve this issue completely.

**Comment by lextm** [comment] 2022-03-01 05:11
Just shipped release 173.0.0. Please upgrade to this release and restart VSCode.

If you test with only `restructuredtext.confPath` set and no other settings, let's see whether there is any error in Esbonio Language Client log.

**Comment by AbstractUmbra** [comment] 2022-03-01 11:27
Sadly 173.0.0 did not correct the issue, see below:
![Code_2022-03-01_11-22-29](https://user-images.githubusercontent.com/16031716/156160448-6836a168-5633-44e3-b48d-790829b49b6e.png)
I attached a screenshot of the full IDE in the event there has been a misunderstanding of the folder structure, but please let me know if you need any further clarity on that!

The error is once again that `${workspaceFolder}/docs/_build/html/guide/topics/threads.html` does not exist. (changed the path to workspaceFolder for brevity).
It continues to think that the `html` directory should be used, when it does not. The build directory should be `${workspaceFolder}/docs/_build/` only.
My manual build process for sphinx is currently:
```sh
cd docs/
sphinx-build -a -E -n -T -W --keep-going . _build
```

This seems to not use the `docs/_build/html` path in any way, is this a config I can override in the extension?

**Comment by AbstractUmbra** [comment] 2022-03-01 22:48
> Thanks. It's desired that we go back to this `_static/scorer.js` issue.
> 
> When you said "I had to manually build the html with the sphinx-build cli", what was the exact sphinx-build command? Can you share that?

```sh
cd docs/
sphinx-build -a -E -n -T -W --keep-going . _build
```

This is currently how I do it.

**Comment by lextm** [comment] 2022-03-02 05:04
If without `cd docs/`, what's the output of `sphinx-build -a -E -n -T -W --keep-going docs docs/_build`? Will that give you the same `_static/scorer.js` error?

**Comment by AbstractUmbra** [comment] 2022-03-02 06:27
Oh, that makes sense! 
Is it possible to override the working directory, or something similar like that? So that it runs within the `docs/` subfolder?

**Comment by AbstractUmbra** [comment] 2023-02-25 11:41
Sorry to bump this old issue, but do you think we're any closer to a solution?

I have found myself needing to write egregious amounts of RST again and this extension would be a real life saver!

**Comment by lextm** [comment] 2024-01-05 07:32
Starting from version 190.1.17, this extension no longer performs live preview but recommends the Esbonio extension to be used instead. Close this issue now.

**Closed by lextm** 2024-01-05 07:32 UTC
Labels: bug, dependency issue, area:preview, area:esbonio
